/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.66
 * Generated at: 2021-06-24 04:48:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("  \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("  font-family: Arial, Helvetica, sans-serif;\r\n");
      out.write("}\r\n");
      out.write("* {\r\n");
      out.write("  box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("/* style the container */\r\n");
      out.write(".container {\r\n");
      out.write("  position: relative;\r\n");
      out.write("  border-radius: 5px;\r\n");
      out.write("  background-color: #f2f2f2;\r\n");
      out.write("  padding: 20px 0 30px 0;\r\n");
      out.write("} \r\n");
      out.write("/* style inputs and link buttons */\r\n");
      out.write("input,\r\n");
      out.write(".btn {\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  padding: 12px;\r\n");
      out.write("  border: none;\r\n");
      out.write("  border-radius: 4px;\r\n");
      out.write("  margin: 5px 0;\r\n");
      out.write("  opacity: 0.85;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  font-size: 17px;\r\n");
      out.write("  line-height: 20px;\r\n");
      out.write("  text-decoration: none; /* remove underline from anchors */\r\n");
      out.write("}\r\n");
      out.write("input:hover,\r\n");
      out.write(".btn:hover {\r\n");
      out.write("  opacity: 1;\r\n");
      out.write("}\r\n");
      out.write("/* add appropriate colors to fb, twitter and google buttons */\r\n");
      out.write(".fb {\r\n");
      out.write("  background-color: #3B5998;\r\n");
      out.write("  color: white;\r\n");
      out.write("}\r\n");
      out.write(".twitter {\r\n");
      out.write("  background-color: #55ACEE;\r\n");
      out.write("  color: white;\r\n");
      out.write("}\r\n");
      out.write(".google {\r\n");
      out.write("  background-color: #dd4b39;\r\n");
      out.write("  color: white;\r\n");
      out.write("}\r\n");
      out.write("/* style the submit button */\r\n");
      out.write("input[type=button] {\r\n");
      out.write("  background-color: #04AA6D;\r\n");
      out.write("  color: white;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("input[type=button]:hover {\r\n");
      out.write("  background-color: #45a049;\r\n");
      out.write("}\r\n");
      out.write("/* Two-column layout */\r\n");
      out.write(".col {\r\n");
      out.write("  float: left;\r\n");
      out.write("  width: 50%;\r\n");
      out.write("  margin: auto;\r\n");
      out.write("  padding: 0 50px;\r\n");
      out.write("  margin-top: 6px;\r\n");
      out.write("}\r\n");
      out.write("/* Clear floats after the columns */\r\n");
      out.write(".row:after {\r\n");
      out.write("  content: \"\";\r\n");
      out.write("  display: table;\r\n");
      out.write("  clear: both;\r\n");
      out.write("}\r\n");
      out.write("/* vertical line */\r\n");
      out.write(".vl {\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  left: 50%;\r\n");
      out.write("  transform: translate(-50%);\r\n");
      out.write("  border: 2px solid #ddd;\r\n");
      out.write("  height: 175px;\r\n");
      out.write("}\r\n");
      out.write("/* text inside the vertical line */\r\n");
      out.write(".vl-innertext {\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  top: 50%;\r\n");
      out.write("  transform: translate(-50%, -50%);\r\n");
      out.write("  background-color: #f1f1f1;\r\n");
      out.write("  border: 1px solid #ccc;\r\n");
      out.write("  border-radius: 50%;\r\n");
      out.write("  padding: 8px 10px;\r\n");
      out.write("}\r\n");
      out.write("/* hide some text on medium and large screens */\r\n");
      out.write(".hide-md-lg {\r\n");
      out.write("  display: none;\r\n");
      out.write("}\r\n");
      out.write("/* bottom container */\r\n");
      out.write(".bottom-container {\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  background-color: #666;\r\n");
      out.write("  border-radius: 0px 0px 4px 4px;\r\n");
      out.write("}\r\n");
      out.write("/* Responsive layout - when the screen is less than 650px wide, make the two columns stack on top of each other instead of next to each other */\r\n");
      out.write("@media screen and (max-width: 650px) {\r\n");
      out.write("  .col {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    margin-top: 0;\r\n");
      out.write("  }\r\n");
      out.write("  /* hide the vertical line */\r\n");
      out.write("  .vl {\r\n");
      out.write("    display: none;\r\n");
      out.write("  }\r\n");
      out.write("  /* show the hidden text on small screens */\r\n");
      out.write("  .hide-md-lg {\r\n");
      out.write("    display: block;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(function(){\r\n");
      out.write("	$(\"#bt_login\").click(function(){\r\n");
      out.write("		login();\r\n");
      out.write("	});\r\n");
      out.write("});\r\n");
      out.write("function login(){\r\n");
      out.write("	$(\"form\").attr({\r\n");
      out.write("		\"action\":\"/member/login\",\r\n");
      out.write("		\"method\":\"post\"\r\n");
      out.write("	});	\r\n");
      out.write("	$(\"form\").submit();\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<h2>Responsive Social Login Form</h2>\r\n");
      out.write("<p>Resize the browser window to see the responsive effect. When the screen is less than 650px wide, make the two columns stack on top of each other instead of next to each other.</p>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("  <form>\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("      <h2 style=\"text-align:center\">Login with Social Media or Manually</h2>\r\n");
      out.write("      <div class=\"vl\">\r\n");
      out.write("        <span class=\"vl-innertext\">or</span>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"col\">\r\n");
      out.write("        <a href=\"#\" class=\"fb btn\">\r\n");
      out.write("          <i class=\"fa fa-facebook fa-fw\"></i> Login with Facebook\r\n");
      out.write("         </a>\r\n");
      out.write("        <a href=\"#\" class=\"twitter btn\">\r\n");
      out.write("          <i class=\"fa fa-twitter fa-fw\"></i> Login with Twitter\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#\" class=\"google btn\"><i class=\"fa fa-google fa-fw\">\r\n");
      out.write("          </i> Login with Google+\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"col\">\r\n");
      out.write("        <div class=\"hide-md-lg\">\r\n");
      out.write("          <p>Or sign in manually:</p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <input type=\"text\" 			name=\"user_id\" 		placeholder=\"Your ID...\" required>\r\n");
      out.write("        <input type=\"password\" 	name=\"password\" 	placeholder=\"Password\" required>\r\n");
      out.write("        <input type=\"button\" value=\"Login\" id=\"bt_login\">\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write("  </form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"bottom-container\">\r\n");
      out.write("  <div class=\"row\">\r\n");
      out.write("    <div class=\"col\">\r\n");
      out.write("      <a href=\"#\" style=\"color:white\" class=\"btn\">Sign up</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col\">\r\n");
      out.write("      <a href=\"#\" style=\"color:white\" class=\"btn\">Forgot password?</a>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
