/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.66
 * Generated at: 2021-06-28 01:51:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.reboard;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.koreait.site0625.model.domain.ReBoard;
import java.util.List;
import com.koreait.site0625.model.reboard.dao.MybatisReBoardDAO;
import com.koreait.site0625.model.reboard.dao.ReBoardDAO;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


	ReBoardDAO reBoardDAO=new MybatisReBoardDAO();

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/reboard/inc/lib.jsp", Long.valueOf(1624610778000L));
    _jspx_dependants.put("/reboard/inc/footer.jsp", Long.valueOf(1624610778000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.koreait.site0625.model.domain.ReBoard");
    _jspx_imports_classes.add("com.koreait.site0625.model.reboard.dao.MybatisReBoardDAO");
    _jspx_imports_classes.add("com.koreait.site0625.model.reboard.dao.ReBoardDAO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write('\n');

	List<ReBoard> boardList=reBoardDAO.selectAll();

      out.write("\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<title>Untitled Document</title>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n");
      out.write("<style>\n");
      out.write("#box{border:1px solid #CCCCCC}\n");
      out.write("#title{font-size:9pt;font-weight:bold;color:#7F7F7F;돋움}\n");
      out.write("#category{font-size:9pt;color:#7F7F7F;돋움}\n");
      out.write("#keyword{\n");
      out.write("	width:80px;\n");
      out.write("	height:17px;\n");
      out.write("	font-size:9pt;\n");
      out.write("	border-left:1px solid #333333;\n");
      out.write("	border-top:1px solid #333333;\n");
      out.write("	border-right:1px solid #333333;\n");
      out.write("	border-bottom:1px solid #333333;\n");
      out.write("	color:#7F7F7F;돋움\n");
      out.write("}\n");
      out.write("#paging{font-size:9pt;color:#7F7F7F;돋움}\n");
      out.write("#list td{font-size:9pt;}\n");
      out.write("#copyright{font-size:9pt;}\n");
      out.write("a{text-decoration:none}\n");
      out.write("img{border:0px}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>");
      out.write("\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<table id=\"box\" align=\"center\" width=\"603\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n");
      out.write("  <tr>\n");
      out.write("    <td colspan=\"5\"><img src=\"/reboard/images/ceil.gif\" width=\"603\" height=\"25\"></td>\n");
      out.write("  </tr>\n");
      out.write("  <tr>\n");
      out.write("    <td height=\"2\" colspan=\"5\" bgcolor=\"#6395FA\"><img src=\"/reboard/images/line_01.gif\"></td>\n");
      out.write("  </tr>\n");
      out.write("  <tr id=\"title\" align=\"center\">\n");
      out.write("    <td width=\"50\" height=\"20\">번호</td>\n");
      out.write("    <td width=\"303\" height=\"20\">제목</td>\n");
      out.write("    <td width=\"100\" height=\"20\">글쓴이</td>\n");
      out.write("    <td width=\"100\" height=\"20\">날짜</td>\n");
      out.write("    <td width=\"50\" height=\"20\">조회수</td>\n");
      out.write("  </tr>\n");
      out.write("  <tr>\n");
      out.write("    <td height=\"1\" colspan=\"5\" bgcolor=\"#CCCCCC\"></td>\n");
      out.write("  </tr>\n");
      out.write("	<tr>	\n");
      out.write("		<td colspan=\"5\" id=\"list\">\n");
      out.write("		  <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n");
      out.write("			");
for( ReBoard reboard : boardList){
      out.write("\n");
      out.write("		    <tr align=\"center\" height=\"20px\" onMouseOver=\"this.style.background='#FFFF99'\" onMouseOut=\"this.style.background=''\">\n");
      out.write("			  <td width=\"50\">1</td>\n");
      out.write("			  <td width=\"303\" style=\"text-align:left;\">\n");
      out.write("			  ");
if(reboard.getDepth()>0){ 
      out.write("\n");
      out.write("			  <img src=\"/reboard/images/re.png\" width=\"20px\" style=\"margin-left:");
      out.print(10*reboard.getDepth());
      out.write("px\">\n");
      out.write("			  	");
} 
      out.write("\n");
      out.write("			  	<a href=\"/reboard/detail.jsp?reboard_id=");
      out.print(reboard.getReboard_id() );
      out.write('"');
      out.write('>');
      out.print(reboard.getTitle() );
      out.write("</a>\n");
      out.write("			  </td>\n");
      out.write("			  <td width=\"100\">");
      out.print(reboard.getWriter() );
      out.write("</td>\n");
      out.write("			  <td width=\"100\">");
      out.print(reboard.getRegdate().substring(0,10) );
      out.write("</td>\n");
      out.write("			  <td width=\"50\">");
      out.print(reboard.getHit() );
      out.write("</td>\n");
      out.write("		    </tr>\n");
      out.write("			<tr>\n");
      out.write("				<td height=\"1\" colspan=\"5\" background=\"/reboard/images/line_dot.gif\"></td>\n");
      out.write("			</tr>\n");
      out.write("			");
} 
      out.write("\n");
      out.write("		  </table>		</td>\n");
      out.write("	</tr>\n");
      out.write("  <tr>\n");
      out.write("    <td id=\"paging\" height=\"20\" colspan=\"5\" align=\"center\">[1][2][3][4][5][6][7][8][9][10]</td>\n");
      out.write("  </tr>\n");
      out.write("  <tr>\n");
      out.write("    <td height=\"20\" colspan=\"5\" align=\"right\" style=\"padding-right:2px;\">\n");
      out.write("	<table width=\"160\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n");
      out.write("      <tr>\n");
      out.write("        <td width=\"70\">\n");
      out.write("          <select name=\"select\" id=\"category\">\n");
      out.write("            <option>제목</option>\n");
      out.write("            <option>내용</option>\n");
      out.write("            <option>글쓴이</option>\n");
      out.write("          </select>        </td>\n");
      out.write("        <td width=\"80\">\n");
      out.write("          <input name=\"textfield\" id=\"keyword\" type=\"text\" size=\"15\">        </td>\n");
      out.write("        <td><img src=\"/reboard/images/search_btn.gif\" width=\"32\" height=\"17\"></td>\n");
      out.write("      </tr>\n");
      out.write("    </table></td>\n");
      out.write("  </tr>\n");
      out.write("  <tr>\n");
      out.write("    <td height=\"30\" colspan=\"5\" align=\"right\" style=\"padding-right:2px;\"><a href=\"write.jsp\"><img src=\"/reboard/images/write_btin.gif\" width=\"61\" height=\"20\" border=\"0\"></a></td>\n");
      out.write("  </tr>\n");
      out.write("  <tr>\n");
      out.write("    <td height=\"1\" colspan=\"5\" bgcolor=\"#CCCCCC\"></td>\n");
      out.write("  </tr>\n");
      out.write("	");
      out.write("\n");
      out.write("<tr>\n");
      out.write("  <td height=\"20\" colspan=\"5\" align=\"center\" id=\"copyright\">Copyright zino All Rights Reserved </td>\n");
      out.write("</tr>\n");
      out.write("\n");
      out.write("</table>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
